apiVersion: v1
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  creationTimestamp: "2023-01-14T15:45:20Z"
  name: currency-conversion
  namespace: default
  resourceVersion: "21249"
  uid: c0d16ab7-40e3-447c-a1c0-fe5b012fc9db
