
apiVersion: apps/v1

kind: Deployment

metadata:

  annotations:
    deployment.kubernetes.io/revision: "1"

  generation: 1

  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
  

spec:
  
  replicas: 2
  
  selector:
    matchLabels:
      app: currency-conversion

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: roshan66/rmdk8-currency-conversion-service:0.0.12-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: rmdk8-currency-conversion-service
        envFrom: 
        - configMapRef: 
            name: currency-conversion
        # env: 
        #   - name: CURRENCY_EXCHANGE_URI
        #     value: http://currency-exchange 
      restartPolicy: Always
  
 
  
---



apiVersion: v1

kind: Service

metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
  
spec:

  ipFamilies:
  - IPv4

  ipFamilyPolicy: SingleStack

  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100

  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer

 

---


apiVersion: v1

data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange

kind: ConfigMap

metadata:
  creationTimestamp: "2023-01-14T15:45:20Z"
  name: currency-conversion
  namespace: default
  resourceVersion: "21249"
  uid: c0d16ab7-40e3-447c-a1c0-fe5b012fc9db








